### ISSUE TITLE
Error: Cannot find module 'jinsta'

### ISSUE THREAD

**Issue by GaWr26** [breuerfelix/jinsta#12]
running `node index.js ` after setting erything up as in the readme results in the following error:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'jinsta'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/jinsta/index.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Starting jinsta directly from CL does work though

**Comment by GaWr26** [comment]
got it working by running `npm i jinsta` and getting the node modules in the current directory.
Seems the path to the global module is not working...

**Comment by breuerfelix** [comment]
done :)
