### ISSUE TITLE
unhandled promise rejection warning

### ISSUE THREAD

**Issue by halalfood** [breuerfelix/jinsta#28]
heres my terminal log. Ran into an issue that stopped the liking.

generate new feed
(node:49920) UnhandledPromiseRejectionWarning: TypeError: this.media.push is not iterable (cannot read property Symbol(Symbol.iterator))
    at CommentFeed.run (C:\Users\Adil\Desktop\instagrambot\node_modules\jinsta\dist\feeds\base.js:34:20)
    at async UserFeed.runNewFeed (C:\Users\Adil\Desktop\instagrambot\node_modules\jinsta\dist\feeds\user.js:72:12)
    at async UserFeed.run (C:\Users\Adil\Desktop\instagrambot\node_modules\jinsta\dist\feeds\base.js:92:11)
    at async CommentFeed.runNewFeed (C:\Users\Adil\Desktop\instagrambot\node_modules\jinsta\dist\feeds\comment.js:75:12)
    at async CommentFeed.run (C:\Users\Adil\Desktop\instagrambot\node_modules\jinsta\dist\feeds\base.js:92:11)
    at async TimelineFeed.runNewFeed (C:\Users\Adil\Desktop\instagrambot\node_modules\jinsta\dist\feeds\timeline.js:72:12)
    at async TimelineFeed.run (C:\Users\Adil\Desktop\instagrambot\node_modules\jinsta\dist\feeds\base.js:92:11)
    at async loop.run (C:\Users\Adil\Desktop\instagrambot\node_modules\jinsta\dist\loop.js:45:5)
(node:49920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:49920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by GaWr26** [comment]
I got this today:
```
(node:17073) UnhandledPromiseRejectionWarning: IgActionSpamError: POST /api/v1/media/2095210727513015946_6864386408/like/ - 400 Bad Request; feedback_required
    at Request.handleResponseError (/home/pi/jinsta/node_modules/instagram-private-api/dist/core/request.js:79:20)
    at Request.send (/home/pi/jinsta/node_modules/instagram-private-api/dist/core/request.js:49:28)
(node:17073) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17073) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Unfortunately I believe this is a block from IG

**Comment by breuerfelix** [comment]
i had some issues with the comment / user feeds but this should be fixed in the new version coming in some minutes ! :)
