### ISSUE TITLE
IgActionSpamError

### ISSUE THREAD

**Issue by GaWr26** [breuerfelix/jinsta#29]
I got this today. Unfortunately I believe it's a block from IG...

```
(node:17073) UnhandledPromiseRejectionWarning: IgActionSpamError: POST /api/v1/media/2095210727513015946_6864386408/like/ - 400 Bad Request; feedback_required
    at Request.handleResponseError (/home/pi/jinsta/node_modules/instagram-private-api/dist/core/request.js:79:20)
    at Request.send (/home/pi/jinsta/node_modules/instagram-private-api/dist/core/request.js:49:28)
(node:17073) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17073) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by breuerfelix** [comment]
if the mentioned PR is merged, try the following:
- run jinsta with `jinsta -r -s my_seed -u bla -p bla`
- if you use advanced config set `config.reset = true` and `config.seed = 'my_seed'
- try if it works :)

if it does work out, try to get the value when you experience a block.  
if it is 30 for example, run the bot twice a day with a limit of 20 and increment this each day by 2 to 5 and see if you hit the limit again

try to reuse your old seed keys from time to time and increase their limit aswell, i would like to know if instagram saves the device id with the interaction limit

**Comment by GaWr26** [comment]
hm Felix, ran it again today with reset and new seed and got the 400 Error again.
Now I see this on App and desktop when trying to log in to Instagram:
![Bildschirmfoto 2019-10-22 um 13 44 14](https://user-images.githubusercontent.com/1381617/67282485-2f934180-f4d2-11e9-9d3f-85444acdda50.png)
How bad is this? Never seen this before...

**Comment by breuerfelix** [comment]
strange... dont think that this is too bad, what happens when you say get help logging in ?

**Comment by GaWr26** [comment]
clicking the link brings me here: https://help.instagram.com/358911864194456
I have no clue what to do about this... will send you my logs

**Comment by mixaxdd** [comment]
same thing happening to me 
it's not a ban 
you mast change password (reset by email)
until you see a request to confirm the information

i used a vpn, and differ browsers
something of this helps me after 30+ iterations
then I saw a new form

my steps:
1. logout
2. login in instagram via browser
3. press forgot password
4. reset by email
5. enter new passwords
6. go to mail and klick on ''secure your account here'' in new letter
repeat 6 again and again with switch vpn

I found it [here](https://vk.com/smm_pub?w=wall-43503600_496065)

**Comment by breuerfelix** [comment]
the question is, why is this happening ? what have you done different than the others ?

have you used many different seeds ?

**Comment by GaWr26** [comment]
Thank you very much @mixaxdd! I got my account back. I used a vpn but not sure if this is really necessary... What a damn dodgy process. I was clicking about with no luck until at some point a page showed up where it showed my profile information and I approved that and now I'm back in. What is this?

Well, never mind. Tomorrow I will start easy again with 10 likes...

**Comment by mixaxdd** [comment]
i used outdated version jinsta - 0.0.14
and i have this error (400 Bad Request)
spammed the error several times
may be it work so fast?
then Instagram detect that i use some illegal service 
i change password and go asleep two days
all is good, i do nothing
no instapy and jinsta
and suddenly this strange block

**Comment by GaWr26** [comment]
Today I ran jinsta gain with limiting likes to 10 with a new seed.
After 9 likes I got  400 Bad Request; feedback_required.

Feels like my account is flaged just as it was using InstaPy.
I hope this is not bad news for the approach and there's a way around this

**Comment by apaticmusic** [comment]
I'm catching this sometimes. Can you make some changes in the code to continue process instead of exit with Exception?

**Comment by GaWr26** [comment]
Better day today. I ran with reset = true and a new seed.
It did 35 likes and ended as expected. Also logs were properly written.

Unfortunately like_limit was ignored which I had set to 8 so there seems to be a bug.

**Comment by mixaxdd** [comment]
I have bloked again. But easy got my account back. Reset password and click in mail "secure your account here" but open it in private window. Yes, confirmation window! Without private window it show block every time.

**Comment by micheledellaguardia** [comment]
I had the same problem, but I saw that jinsta is accessing Instagram every time with a different user agent.
Here are a couple of security confirmation email I got from Ig:

![Cattura_1256](https://user-images.githubusercontent.com/36262776/68143592-15298100-ff32-11e9-911f-51d53ddfe958.JPG)

![Cattura_1308](https://user-images.githubusercontent.com/36262776/68143642-296d7e00-ff32-11e9-84d9-a0a882b267cb.JPG)

Is there a way to force a single user agent for any session, as should be using just my own mobile device? With an always different user agent i think it's easier for Ig to suspect of a bot activity.
Thanks a lot

**Comment by breuerfelix** [comment]
do you always use the same seed ? or do you change it ? 

it should use the same user agent with the same seed / username :) but let me know !

**Comment by micheledellaguardia** [comment]
Hi, I had to change the seed (-r -s newseed) because of a IgActionSpamError, but after that I got this on Instagram App and a SMS/Confirmation code request on Jinsta. Is there a way to force a user agent even changing the seed?
