### ISSUE TITLE
Exception right after start-up

### ISSUE THREAD

**Issue by Timiboy27** [breuerfelix/jinsta#32]
Hey I´ve freshly installed Jinsta to give it a try after InstaPy but when I start Jinsta with 

> jinsta -u username -p password -w ./jinsta_data

I get an error which says the following:

> (node:17744) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'username' of null
    at TimelineFeed.getMoreMedia (Roaming\npm\node_modules\jinsta\dist\feeds\timeline.js:39:91)
    at TimelineFeed.run (Roaming\npm\node_modules\jinsta\dist\feeds\base.js:35:37)
    at loop.run (Roaming\npm\node_modules\jinsta\dist\loop.js:56:20)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:412:9)
(node:17744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17744) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:17744) UnhandledPromiseRejectionWarning: IgLoginRequiredError: GET /api/v1/users/arlink_download_info/?version_override=2.0.2 - 403 Forbidden; login_required
    at Request.handleResponseError (Roaming\npm\node_modules\jinsta\node_modules\instagram-private-api\dist\core\request.js:90:24)
    at Request.send (Roaming\npm\node_modules\jinsta\node_modules\instagram-private-api\dist\core\request.js:49:28)
    at async UserRepository.arlinkDownloadInfo (Roaming\npm\node_modules\jinsta\node_modules\instagram-private-api\dist\repositories\user.repository.js:13:26)
(node:17744) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

Any idea how to fix this? What am I doing wrong?

**Comment by breuerfelix** [comment]
fixed it in the latest version :)

it will be published in about 2 minutes!
