### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by micheledellaguardia** [breuerfelix/jinsta#35]
Hi,
today I tried to install and run jinsta (Ubuntu Linux 18.04) and soon had this error :
---
jinsta -u myusername -p mypassword -w /jinsta_data

/usr/local/lib/node_modules/jinsta/dist/session.js:48
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/jinsta/dist/loop.js:16:39)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/jinsta/dist/index.js:34:36)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
---
How may I solve it?
Thanks a lot

**Comment by breuerfelix** [comment]
what is your node version ? check it with `node --version`

i guess it is version 8, right now you need at least version 10 :) but i can try to fix that !

**Comment by micheledellaguardia** [comment]
yes, it's version 8. Didn't know about minimal requirements, sorry ;) Hope you can fix it anyway.
Thanks a lot

**Comment by breuerfelix** [comment]
should be already fixed :) could you try it out ?

**Comment by micheledellaguardia** [comment]
Hi, yes, it's working flawless now after an update :)
Thanks a lot for you work!

**Comment by breuerfelix** [comment]
no problem ! was just a small change but i was targetting node 12 .... a little too high :D
