### ISSUE TITLE
Too many reels requested during StoryMassView

### ISSUE THREAD

**Issue by imkimchi** [breuerfelix/jinsta#65]
Nothing special in my code. All I did was `setup` and `storyMassView`.

and I got this error below

```
info:    starting vieweing stories from story feed
(node:30629) UnhandledPromiseRejectionWarning: IgResponseError: POST /api/v1/feed/reels_media/ - 400 Bad Request; Too many reels requested 
    at Request.handleResponseError (/mnt/c/Users/wbvco/Desktop/jinsta/node_modules/instagram-private-api/src/core/request.ts:138:12)       
    at Request.send (/mnt/c/Users/wbvco/Desktop/jinsta/node_modules/instagram-private-api/src/core/request.ts:77:24)
(node:30629) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30629) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by imkimchi** [comment]
https://github.com/breuerfelix/jinsta/issues/34

**Comment by breuerfelix** [comment]
damn, it seems like i dont have as many friends as you have :D thats why i didnt got this error

thanks for reporting!

**Comment by imkimchi** [comment]
my acc is following 500 accounts and there were about 60 stories, I guess It was pretty obvious to get blocked from requests to see all the stories at the same time! we'd need some delays

**Comment by breuerfelix** [comment]
should be fixed now :)
