### ISSUE TITLE
UnhandledPromiseRejectionWarning: IgLoginRequiredError

### ISSUE THREAD

**Issue by EdinCitaku** [breuerfelix/jinsta#75]
Hey,
I am getting this error when starting the bot.
```
info:    logging in with user: username ...
(node:19386) UnhandledPromiseRejectionWarning: IgLoginRequiredError: GET /api/v1/users/arlink_download_info/?version_override=2.0.2 - 403 Forbidden; login_required
    at Request.handleResponseError (/usr/lib/node_modules/jinsta/node_modules/instagram-private-api/dist/core/request.js:93:24)
    at Request.send (/usr/lib/node_modules/jinsta/node_modules/instagram-private-api/dist/core/request.js:49:28)
    at async UserRepository.arlinkDownloadInfo (/usr/lib/node_modules/jinsta/node_modules/instagram-private-api/dist/repositories/user.repository.js:13:26)
(node:19386) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19386) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I don't quite understand what the problem is, I tried it in different networks, the username and password work for sure as I already tried them when manually logging in.
I tried also with installing from source but the same error prevails.
Thanks for your help!

**Comment by beautyfree** [comment]
same

**Comment by beautyfree** [comment]
https://github.com/dilame/instagram-private-api/issues/976

**Comment by EdinCitaku** [comment]
So it randomly started working, and I can not explain why.
Try adding config.seed="<somevalue>" in the index.ts file.
Honestly I already did that and it didnt work, but somehow just now it started working so I cant explain what made it work for me.
