### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by papillon-unix** [breuerfelix/jinsta#76]
I'm getting this on raspberry :

```
(node:1471) UnhandledPromiseRejectionWarning: IgLoginRequiredError: GET /api/v1/loom/fetch_config/ - 403 Forbidden; login_required
    at Request.handleResponseError (/home/pi/node_modules/instagram-private-api/dist/core/request.js:93:24)
    at Request.send (/home/pi/node_modules/instagram-private-api/dist/core/request.js:49:28)
    at async LoomRepository.fetchConfig (/home/pi/node_modules/instagram-private-api/dist/repositories/loom.repository.js:6:26)
(node:1471) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1471) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by die-tueftelei** [comment]
same error on OSX for me:

  logging in with user: xxxxxx ...
? Enter sms / email code: 123456
(node:844) UnhandledPromiseRejectionWarning: IgLoginRequiredError: GET /api/v1/discover/topical_explore/?is_prefetch=true&omit_cover_media=false&use_sectional_payload=true&timezone_offset=3600&session_id=1af6ed0f-fff2-5ec3-a3a7-599714c18f4b&include_fixed_destinations=false - 403 Forbidden; login_required
    at Request.handleResponseError (/Users/p373r/myinsta/node_modules/instagram-private-api/dist/core/request.js:93:24)
    at Request.send (/Users/p373r/myinsta/node_modules/instagram-private-api/dist/core/request.js:49:28)
    at async DiscoverRepository.topicalExplore (/Users/p373r/myinsta/node_modules/instagram-private-api/dist/repositories/discover.repository.js:15:26)
(node:844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ZackMitkin** [comment]
Same thing, tried on windows 10, and ubuntu

`info:    logging in with user: xxxxxx ...
(node:665) UnhandledPromiseRejectionWarning: IgLoginRequiredError: GET /api/v1/fbsearch/recent_searches/ - 403 Forbidden; login_required
    at Request.handleResponseError (/root/.nvm/versions/node/v12.13.0/lib/node_modules/jinsta/node_modules/instagram-private-api/dist/core/request.js:93:24)
    at Request.send (/root/.nvm/versions/node/v12.13.0/lib/node_modules/jinsta/node_modules/instagram-private-api/dist/core/request.js:49:28)
    at async FbsearchRepository.recentSearches (/root/.nvm/versions/node/v12.13.0/lib/node_modules/jinsta/node_modules/instagram-private-api/dist/repositories/fbsearch.repository.js:15:26)
(node:665) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:665) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by breuerfelix** [comment]
i made some issue with the config seed... it should be fixed in the new release :)

**Comment by papillon-unix** [comment]
works great after update, thx 👍

**Comment by die-tueftelei** [comment]
works for me too, updated and deactivated 2factor auth....
