### ISSUE TITLE
400 Bad Request; feedback_required

### ISSUE THREAD

**Issue by papillon-unix** [breuerfelix/jinsta#78]
Hi
At some moment, while puting likes to a tag feed, this error occurs : 

```
info:    got 27 more media for user '**************'
info:    current progress: 1 / 27
info:    current progress: 2 / 27
info:    current progress: 3 / 27
info:    current progress: 4 / 27
info:    current progress: 5 / 27
/home/pi/Bots/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

IgActionSpamError: POST /api/v1/media/2182728920755174918_4057438687/like/ - 400 Bad Request; feedback_required
    at Request.handleResponseError (/home/pi/Bots/node_modules/instagram-private-api/dist/core/request.js:79:20)
    at Request.send (/home/pi/Bots/node_modules/instagram-private-api/dist/core/request.js:49:28)
    at async MediaRepository.likeAction (/home/pi/Bots/node_modules/instagram-private-api/dist/repositories/media.repository.js:56:26)
    at async MergeMapSubscriber.project (/home/pi/Bots/node_modules/jinsta/dist/streams/like.js:61:16)
```

**Comment by papillon-unix** [comment]
And in another account I sometimes get this one :

```
[32minfo[39m:    starting hashtag feed for tag: ********. randomized number of likes: 1.
(node:30166) UnhandledPromiseRejectionWarning: RequestError: Error: connect ETIMEDOUT 157.240.21.63:443
    at Request.faultTolerantRequest (/home/pi/Bots/node_modules/instagram-private-api/dist/core/request.js:112:19)
(node:30166) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:30166) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
