### ISSUE TITLE
403 Forbidden; login_required

### ISSUE THREAD

**Issue by GaWr26** [breuerfelix/jinsta#8]
```
ineedfriends -u xxx -p xxx -s ./session.json
start running basefeed
(node:13008) UnhandledPromiseRejectionWarning: IgLoginRequiredError: POST /api/v1/feed/timeline/ - 403 Forbidden; login_required
    at Request.handleResponseError (/usr/lib/node_modules/ineedfriends/node_modules/instagram-private-api/dist/core/request.js:90:24)
    at Request.send (/usr/lib/node_modules/ineedfriends/node_modules/instagram-private-api/dist/core/request.js:49:28)
(node:13008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:13008) UnhandledPromiseRejectionWarning: IgLoginRequiredError: GET /api/v1/direct_v2/ranked_recipients/?mode=raven&query=&show_threads=true - 403 Forbidden; login_required
    at Request.handleResponseError (/usr/lib/node_modules/ineedfriends/node_modules/instagram-private-api/dist/core/request.js:90:24)
    at Request.send (/usr/lib/node_modules/ineedfriends/node_modules/instagram-private-api/dist/core/request.js:49:28)
(node:13008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Must have something to do with the special characters in my password. It replaces it with something from crontab. Maybe some quotes around the password might help?

**Comment by breuerfelix** [comment]
i just changed alot, also somethings about session handling, could you update and try again please ? :)

**Comment by GaWr26** [comment]
No luck Felix. I have a hyphen(-) in my password and this seems to mess it up. tried single and double quotes and even escaping

**Comment by GaWr26** [comment]
Just changed my password to only alphanumeric and still get the same error

**Comment by vinigabriel** [comment]
+1 from me

**Comment by vinigabriel** [comment]
```
jinsta -u "*****" -p "*****" -s ./session.json
start running basefeed
(node:2961) UnhandledPromiseRejectionWarning: IgLoginRequiredError: GET /api/v1/direct_v2/ranked_recipients/?mode=raven&query=&show_threads=true - 403 Forbidden; login_required
    at Request.handleResponseError (/usr/local/lib/node_modules/jinsta/node_modules/instagram-private-api/dist/core/request.js:90:24)
    at Request.send (/usr/local/lib/node_modules/jinsta/node_modules/instagram-private-api/dist/core/request.js:49:28)
(node:2961) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2961) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2961) UnhandledPromiseRejectionWarning: IgLoginRequiredError: POST /api/v1/feed/timeline/ - 403 Forbidden; login_required
    at Request.handleResponseError (/usr/local/lib/node_modules/jinsta/node_modules/instagram-private-api/dist/core/request.js:90:24)
    at Request.send (/usr/local/lib/node_modules/jinsta/node_modules/instagram-private-api/dist/core/request.js:49:28)
(node:2961) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by breuerfelix** [comment]
i am currently changing the code so you can import the package and hard code the username / pw in your own nodejs file... that way we can determine where the error is :) maybe its the cli parser... i dont know yet :D

**Comment by breuerfelix** [comment]
try update :)

`npm update -g jinsta`

i fixed it now ! had the same problem on my machine and it works now :)

but if its still not working, could you try out the advanced configuration option and make a new issue ? cause this will be interesting then !
